function get_comments_list() {
	return [
		{cat: "Trifecta 3", text:"Check choke/pattern – Multiple misses in pattern (Red in circle on 'Money Shot')"},
		{cat: "Trifecta 3", text:"Aim Lower – Aimpoint was ‘Over’ in much of round (See 'Ovr' in 'Round Statistics')"},
		{cat: "Trifecta 3", text:"Aim Higher – Aimpoint was ‘Under’ in much of round (See 'Und' in 'Round Statistics')"},
		{cat: "Trifecta 3", text:"Lead More – Many shots were ‘Behind’ (See 'Bhd' in 'Round Statistics')"},
		{cat: "Trifecta 3", text:"Lead Less – Many shots were ‘Ahead’ (See 'Ahd' in 'Round Statistics')"},
		{cat: "Trifecta 3", text:"Improve Swing Consistency – Swings should have one consistent shape (See ‘Swing Velocity’). Develop one swing style for all shots."},
		{cat: "Trifecta 3", text:"Improve Aim Consistency – Aim accuracy can be improved (Reduce spread in ‘Money Shot’). Practice pointing drills."},
		{cat: "Trifecta 3", text:"Improve Swing Smoothness – Swings are mostly one shape [GOOD]; but, note waviness in red lines, indicates tense swing (See ‘Swing Velocity’)."},
		{cat: "Trifecta 3", text:"Improve Hold prior to 'Pull' – Reduced movement prior to shot will help to improve consistency"},
		{cat: "Trifecta 3", text:"Rushing Into Shot – Your time to shoot is significantly quicker than most shooters. This rushed timing contributtes to aiming issues."},
		{cat: "Trifecta 3", text:"Improve Follow Through – Many shots have a jerk just prior to shot."},
		{cat: "Trifecta 3", text:"Improve Follow Through – Swing stops at shot with many shots, swing through trigger pull (See 'Swing Velocity)."},
		{cat: "Trifecta 3", text:"Improve Follow Through – Swing after shot is not consistent with swing prior to trigger pull (See Gun PoV videos)."},
		{cat: "Trifecta 3", text:"Check Gun Fit – Sight line is not aligned with gun, Right or Left values in 'Round Statistics' are high."},
		{cat: "Trifecta 3", text:"Check Gun Fit – Sight line is not aligned with gun, Up or Down values in 'Round Statistics' are high."},
		{cat: "Trifecta 3", text:"Focus on Passing Shots – More frequent misses on Hard Left &/or Right passing shots. Practice swing and point drills"},
		{cat: "Accuracy", text:"Work with your coach to improve your pointing accuracy ... Practice pointing drills, evaluate gun fit."},
		{cat: "Accuracy", text:"Pointing consistency drills: http://www.range365.com/three‐ways‐improve‐your‐shotgun‐skills‐home."},
		{cat: "Accuracy", text:"Coach: Evaluate if the gun is too heavy or hard for her to swing"},
		{cat: "Accuracy", text:"Look to reduce spread outside shaded circle in Money Shot ... This is where you'll see results of your pointing improvement."},
		{cat: "Accuracy", text:"Aim Point stats show that your gun mounting is not consistent ... Left/Right values are too high"},
		{cat: "Accuracy", text:"Aim Point stats show that your gun mounting is not consistent ... Left/Right &/or Over/Under"},
		{cat: "Accuracy", text:"Work with drills to improve pointing consistency, such as: http://www.range365.com/three‐ways‐improve‐your‐shotgun‐skills‐home"},
		{cat: "Accuracy", text:"Look to reduce spread outside shaded circle (See Money Shot). Pointing Consistency is where you'll see the most benefit"},
		{cat: "Aimpoint", text:"Improve your aim consistency to improve your performance ... note 'On %' is low (see ON in Aim Point table)"},
		{cat: "Aimpoint", text:"Good 'On' % ... Your aim is on target %EQN1%% of the time, good work!"},
		{cat: "Aimpoint", text:"Very Good 'On' % ... Your aim is on target %EQN1%% of the time, good work!"},
		{cat: "Aimpoint", text:"Excellent 'On' % ... Your aim is on target %EQN1%% of the time, good work!"},
		{cat: "Aimpoint", text:"You are pointing Right of target much more often than Left (See Aim Point Table, Rt is much higher than Lft value)"},
		{cat: "Aimpoint", text:"You are pointing Left of target much more often than Right (See Aim Point Table, Lft is much higher than Rt value)"},
		{cat: "Aimpoint", text:"Shooting Over target... Evaluate gun fit. Not sighting straight down gun, mounting too low on shoulder &/or lifting head at shot"},
		{cat: "Aimpoint", text:"Shooting Under target... Evaluate gun fit. Not sighting straight along sight plane &/or mounting too high on shoulder"},
		{cat: "Aimpoint", text:"Lead the clay more to improve performance ... note 'Behind' is high (see 'Bhd' in Aim Point table)"},
		{cat: "Aimpoint", text:"Lead the clay less to improve performance ... note 'Ahead' is high (see 'Ahd' in Aim Point table)"},
		{cat: "Aimpoint", text:"Overall Aim is balanced around clay (Aim Point statistics are generally low)"},
		{cat: "Aimpoint", text:"[GOOD] No overall issues with aim ... 'On%' is high as compared to other Aim Point values."},
		{cat: "Comparison", text:"(GOOD) Generally Smoother swing this week over last (red lines are smoother), see Swing Velocity"},
		{cat: "Comparison", text:"(OPPORTUNITY) Swing smoothness is worse this week over last (red lines are wavy), see Swing Velocity"},
		{cat: "Comparison", text:"(GOOD) Generally better aim accuracy this week over last time (Clay grouping is tighter around aimpoint), see Money Shot"},
		{cat: "Comparison", text:"(OPPORTUNITY) Aim accuracy this week is not as good as last time (Clays are spread farther out around aimpoit), see Money Shot"},
		{cat: "Flight Dir", text:"Flight Direction: Slightly lower hit percentage on higher angle (L/R & R/L) shots than straightaways (C) ... Focus on higher angle shots."},
		{cat: "Flight Path", text:"Work other areas first ... this will be a focus in the future"},
		{cat: "Flight Path", text:"You tend to miss left flying targets more ... Evaluate your hold point for shots in 'Round Summary' (on portal)"},
		{cat: "Flight Path", text:"You tend to miss right flying targets more ... Evaluate your hold point for shots in 'Round Summary' (on portal)"},
		{cat: "Flight Path", text:"You are missing more on passing shots (L/R &/or R/L). Work on consistently leading the clay &/or improving pointing accuracy."},
		{cat: "Flight Path", text:"You are missing more on straightaway (center) shots. Work on your hold point on these clays."},
		{cat: "Flight Path", text:"No preference seen for one angle type ... no concentration of misses in a specific direction; Focus on other areas"},
		{cat: "General", text:"No overall issues with aim."},
		{cat: "Money Shot", text:"Also, your Left & Right Stat shows you can improve your aim (too much variation where you aim)"},
		{cat: "Money Shot", text:"[GOOD] Nice grouping on Money Shot ... Good pointing consistency."},
		{cat: "Money Shot", text:"Check your pattern & Choke ... There are multiple misses (RED) inside your pattern (shaded, shot circle)."},
		{cat: "Money Shot", text:"Good grouping in Money Shot. Further improvement possible by pointing slightly lower ... most clays are below pattern's center"},
		{cat: "Money Shot", text:"Good grouping in Money Shot. Further improvement possible by pointing slightly higher ... most clays are above pattern's center"},
		{cat: "Money Shot", text:"Good grouping in Money Shot. Further improvement possible by pointing slightly left ... most clays are left of pattern's center"},
		{cat: "Money Shot", text:"Good grouping in Money Shot. Further improvement possible by pointing slightly right ... most clays are right of pattern's center"},
		{cat: "Round Summary", text:"[GOOD] Hold points are consistent, stationary with good hold positions on traphouse."},
		{cat: "Round Summary", text:"Improve swing path efficiency ... Swing straight to clay position at shot, reduce weaving."},
		{cat: "Velocity", text:"[GOOD] Generally One swing shape ... indicates that you have consistency in your swing, which is good."},
		{cat: "Velocity", text:"Swing smoothness can be improved ... wiggle in red line (your gun swing speed) indicate unstable swing."},
		{cat: "Velocity", text:"Work to swing smoothly through clay... Note swing speed (red line) increases considerably close to trigger pull (right edge of graph)"},
		{cat: "Velocity", text:"[GOOD] You have a steady hold prior to 'Pull' generally Smooth swing (red line is smooth), see Swing Velocity graph."},
		{cat: "Velocity", text:"[GOOD] You have a generally Smooth swing (red line is smooth), see Swing Velocity graph."},
		{cat: "Velocity", text:"Focus on a smooth swing and follow through ... this will improve pointing consistency"},
		{cat: "Velocity", text:"Work to improve stability of hold point prior to 'Pull' ... want near zero velocity in red line on left before starting swing on clay"},
		{cat: "Velocity", text:"Work to improve swing smoothness (wavyiness in red line) ... swinging to & through the target."},
		{cat: "Velocity", text:"Work for same swing shape for all shots (again see graphic) ... just looking for consistency here, not a specific shape."},
		{cat: "Velocity", text:"Generally Smooth swing, which is desirable"},
		{cat: "Velocity", text:"Adjust swing to achieve one, consistent shape ... Typical shape: Still prior to 'Pull', Highest velocity in middle, & Slowing prior to shot"},
		{cat: "Velocity", text:"Swing Velocity (2 pages later): Only focus on a smooth swing it will improve pointing consistency."},
		{cat: "Velocity", text:"Develop one swing ... It is important for consistency."},
		{cat: "Velocity", text:"Gun Speed is rapidly iNCREASING as you fire. You are doing 'final aim correction' as you shoot, not good for consistent performance."},
		{cat: "Velocity", text:"Gun Speed is rapidly DECREASING as you fire. You are not following through not good for consistent performance."},
		{cat: "Velocity", text:"Very nice, smooth swings. One of the better 'swing styles' of anyone on the team."}
	        ];
}
